# Generated by Django 2.2.7 on 2019-11-23 23:46

import datetime
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list = []

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Untitled Feature", max_length=50)),
                ("slug", models.SlugField(default="untitled-feature")),
                (
                    "turn_duration",
                    models.DurationField(default=datetime.timedelta(seconds=120)),
                ),
                ("queue_id", models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
