# Generated by Django 2.2.7 on 2019-11-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live", "0002_remove_feature_queue_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaPlayer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_name", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
