# Generated by Django 2.2.7 on 2019-11-28 03:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live", "0003_mediaplayer"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="current_guests",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
