# Generated by Django 2.2.2 on 2019-06-06 03:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("eventvr", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="guest_queue",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100), default=list, size=None
            ),
        )
    ]
