# Generated by Django 2.2.1 on 2019-05-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("eventvr", "0002_auto_20190514_1043")]

    operations = [
        migrations.RenameModel(
            old_name="DisplayClient", new_name="MediaDisplayerClient"
        )
    ]
