# Generated by Django 2.2.1 on 2019-05-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("eventvr", "0002_mediaplayerconnection")]

    operations = [
        migrations.AlterField(
            model_name="mediaplayerconnection",
            name="channel_name",
            field=models.CharField(blank=True, editable=False, max_length=200),
        )
    ]
