# Generated by Django 2.2.2 on 2019-06-10 12:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("eventvr", "0002_auto_20190606_0316")]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="guest_queue",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        )
    ]
