# Generated by Django 2.2.1 on 2019-05-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("eventvr", "0003_auto_20190519_1715")]

    operations = [
        migrations.CreateModel(
            name="InteractorClient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=100)),
            ],
        )
    ]
