# Generated by Django 2.2.1 on 2019-05-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("eventvr", "0004_interactorclient")]

    operations = [
        migrations.RenameModel(old_name="InteractorClient", new_name="InteractorQueue")
    ]
