# Generated by Django 2.2.1 on 2019-05-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("eventvr", "0005_auto_20190522_1244")]

    operations = [
        migrations.RenameModel(old_name="InteractorQueue", new_name="InteractorClient")
    ]
