# Generated by Django 2.2.1 on 2019-05-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("eventvr", "0006_auto_20190522_1247")]

    operations = [
        migrations.AddField(
            model_name="interactorclient",
            name="available",
            field=models.BooleanField(default=False),
        )
    ]
