# Generated by Django 2.2.1 on 2019-05-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("eventvr", "0007_interactorclient_available")]

    operations = [
        migrations.AlterField(
            model_name="interactorclient",
            name="session_key",
            field=models.CharField(max_length=100, unique=True),
        )
    ]
