# Generated by Django 2.2.1 on 2019-05-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("eventvr", "0008_auto_20190522_2100")]

    operations = [
        migrations.AlterField(
            model_name="interactorclient",
            name="display_name",
            field=models.CharField(default="Anonymous", max_length=100),
        )
    ]
